export const dashboardActions = {
  SWITCH_DASHBOARD: "SWITCH_DASHBOARD",
  UPDATE_DASHBOARD: "UPDATE_DASHBOARD",
  UPDATE_DASHBOARD_REFRESH: "UPDATE_DASHBOARD_REFRESH",
  UPDATE_SELECTEDDASHBOARD_REFRESH: "UPDATE_SELECTEDDASHBOARD_REFRESH",
  ADD_DASHBOARD: "ADD_DASHBOARD",
  UPDATE_PANELS: "UPDATE_PANELS",
  EDIT_LAYOUT: "EDIT_LAYOUT",
  ADD_FILTER: "ADD_FILTER",
  ADD_FILTERPANELLVL: "ADD_FILTERPANELLVL",
  UPDATE_LAST_REFRESH: "UPDATE_LAST_REFRESH",
  UPDATE_REFRESH_RATE_VALUE: "UPDATE_REFRESH_RATE_VALUE",
  UPDATE_MANUAL_REFRESH: "UPDATE_MANUAL_REFRESH",
  FILTERED_NAME: "FILTERED_NAME",
  FILTER_DASHBOARD_NAMES: "FILTER_DASHBOARD_NAMES",
  SEARCH_DASHBOARD_NAMES: "SEARCH_DASHBOARD_NAMES",
  STORE_CHART_DATA: "STORE_CHART_DATA",
  STORED_DASHBOARD_DATA: "STORED_DASHBOARD_DATA",
  STORED_PANNEL_DATA: "STORE_PANNEL_DATA",
  DATA_SRC_NAME: "DATA_SRC_NAME",
  UPDATE_SELECTED_DASHBOARD: "UPDATE_SELECTED_DASHBOARD",
  UPDATE_ALL_DASHBOARDS: "UPDATE_ALL_DASHBOARDS",
  UPDATE_ISPOPUP_ENABLED : "UPDATE_ISPOPUP_ENABLED",
  UPDATE_ISBARCHART_CLICKED : "UPDATE_ISBARCHART_CLICKED"
};

export const administrationActions = {
  GET_ALL_USERS : "GET_ALL_USERS",
  UPDATE_GROUP:'UPDATE_GROUP',
  UPDATE_ORGANIZATION:"UPDATE_ORGANIZATION",
   getAllenterprises:"getAllenterprises",
   GET_ALL_ORG:"GET_ALL_ORG",
   GET_ALL_GROUPS:"GET_ALL_GROUPS",
   GET_ALL_DATASOURCES:"GET_ALL_DATASOURCES"
}

export const enterpriseActions = {
  GET_ALL_USERS: "GET_ALL_USERS",
  GET_ALL_DOMAINS: "GET_ALL_DOMAINS",
  UPDATE_DOMAIN: "UPDATE_DOMAIN",
  UPDATE_GROUP: "UPDATE_GROUP",
  UPDATE_ORGANIZATION: "UPDATE_ORGANIZATION",
  getAllenterprises: "getAllenterprises",
};

export const dashboardTableActions = {
  GET_ALL_DASHBOARDS: "GET_ALL_DASHBOARDS",
  UPDATE_DASHBOARD: "UPDATE_DASHBOARD",
  getAlldashboards: "getAlldashboards",
  DELETE_DASHBOARD: "DELETE_DASHBOARD",
};

export const mainActions = {
  SIDEBAR_FLAG: "SIDEBAR_FLAG"
}
