spring.application.name=API-GATEWAY

server.port=9191
#Making API-Gateway as Client to the Eureka Server
# Get the Below Eureka Server Url in the console of the  erueka server application
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

management.endpoints.web.exposure.include=*
# (Optional) Disable Zipkin if not running
management.tracing.export.zipkin.enabled=false



# Routes For Employee Service  [http://localhost:9191/api/employees]
spring.cloud.gateway.routes[0].id=EMPLOYEE-SERVICE

#  lb = Load balancer , Service Registry Id Respectively
spring.cloud.gateway.routes[0].uri=lb://EMPLOYEE-SERVICE

spring.cloud.gateway.routes[0].predicates[0]=Path=/api/employees/**


# Routes For Department Service  [http://localhost:9191/api/departments]
spring.cloud.gateway.routes[1].id=DEPARTMENT-SERVICE

#  lb = Load balancer , Service Registry Id Respectively
spring.cloud.gateway.routes[1].uri=lb://DEPARTMENT-SERVICE

spring.cloud.gateway.routes[1].predicates[0]=Path=/api/departments/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/api/departments/(?<segment>.*), /api/departments/${segment}

